version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
      day: "friday"
    open-pull-requests-limit: 10
    assignees:
      - joel1di1
    labels:
      - dependencies
      - ruby
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: "friday"
    open-pull-requests-limit: 10
    assignees:
      - joel1di1
    labels:
      - dependencies
      - ruby
