AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'

require:
  - rubocop-rspec

inherit_from:
  - .rubocop_todo.yml


Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true
