inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec
  - rubocop-rails
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "bin/*"

Style/Documentation:
  Enabled: false

RSpec/DescribedClass:
  Enabled: true
  EnforcedStyle: explicit

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false
