inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "bin/*"

Style/Documentation:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false
