require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails

inherit_from:
  - .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'

Style/Documentation:
  Enabled: false
