AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'

require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails

inherit_from:
  - .rubocop_todo.yml

Style/FrozenStringLiteralComment:
  Enabled: true
