language: ruby
rvm:
- 2.1.1
cache: bundler
script:
- RAILS_ENV=test bundle exec rake
deploy:
  provider: heroku
  api_key:
    secure: UMOlEJR4BDdsvwzgdegb7n1BXwxyC2V1IATftmHxiDp79t5LzJlK59RXlkoZn1HI9ybR6L2X+t9CDMtxwjaa75YIj8jbksvpnzfwkztEs1iLWAMECrDS+e0xjJc0XI/Qf71h2FYPyqAt6OdWVvzbwNWM0ctlL14V33sgURSTnhk=
  app: martigua2
  on:
    repo: joel1di1/martigua2
