version: '3.3'
services:
  postgres:
    image: postgres:14
    container_name: postgres_martigua2
    ports:
     - '127.0.0.1:54321:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ${PWD}/db:${PWD}/db
  redis:
    image: redis:7
    ports:
      - '127.0.0.1:63791:6379'
    container_name: redis_martigua2
