version: '2'
services:
  postgres:
    image: postgres:9.6.11
    ports:
      - '127.0.0.1:5432:5432'
    container_name: postgres_martigua2
    environment:
      POSTGRES_USER: martigua2
    volumes:
      - ${PWD}/db:${PWD}/db
  redis:
    image: redis:3.2.12
    ports:
      - '127.0.0.1:6379:6379'
    container_name: redis_martigua2
