version: '3.3'
services:
  postgres:
    image: postgres:13
    container_name: postgres_martigua3
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ${PWD}/db:${PWD}/db
  redis:
    image: redis:3.2.12
    ports:
      - '127.0.0.1:6379:6379'
    container_name: redis_martigua3
