default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  port: <%= ENV.fetch('POSTGRES_PORT', 54321) %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  username: postgres
  password: postgres

development:
  <<: *default
  database: martigua2_development

test:
  <<: *default
  database: martigua2_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>
