version: 1

update_configs:
  - package_manager: "ruby:bundler"
    update_schedule: "weekly"
    directory: "/"
    target_branch: "master"
    allowed_updates:
      - match:
          update_type: "all"
          dependency_type: "direct"
      - match:
          update_type: "security"
          dependency_type: "indirect"
    ignored_updates:
      - match:
          dependency_name: "webpack-rails"
    version_requirement_updates: "auto"
    default_assignees:
      - "joel1di1"
    default_labels:
      - "dependencies"
      - "ruby"
