# frozen_string_literal: true

# Solid Cable table, in the primary database (see issue #1191).
# Body copied verbatim from db/cable_schema.rb generated by solid_cable:install.
class CreateSolidCableMessages < ActiveRecord::Migration[7.2]
  def up
    create_table 'solid_cable_messages' do |t|
      t.binary 'channel', limit: 1024, null: false
      t.binary 'payload', limit: 536_870_912, null: false
      t.datetime 'created_at', null: false
      t.integer 'channel_hash', limit: 8, null: false
      t.index ['channel'], name: 'index_solid_cable_messages_on_channel'
      t.index ['channel_hash'], name: 'index_solid_cable_messages_on_channel_hash'
      t.index ['created_at'], name: 'index_solid_cable_messages_on_created_at'
    end
  end

  def down
    drop_table 'solid_cable_messages'
  end
end
