# frozen_string_literal: true

# Solid Cache table, in the primary database (see issue #1191).
# Mirrors db/cache_structure.sql generated by solid_cache:install.
class CreateSolidCacheEntries < ActiveRecord::Migration[7.2]
  def up
    create_table 'solid_cache_entries' do |t|
      t.binary 'key', null: false
      t.binary 'value', null: false
      t.datetime 'created_at', null: false
      t.bigint 'key_hash', null: false
      t.integer 'byte_size', null: false
      t.index ['byte_size'], name: 'mtg_index_solid_cache_entries_on_byte_size'
      t.index ['key_hash'], name: 'mtg_index_solid_cache_entries_on_key_hash', unique: true
      t.index %w[key_hash byte_size], name: 'mtg_index_solid_cache_entries_on_key_hash_and_byte_size'
    end
  end

  def down
    drop_table 'solid_cache_entries'
  end
end
