name: Rubocop

on: [push]

jobs:
  build:
    name: Rubocop checks
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Rubocop checks
        uses: gimenete/rubocop-action@1.0
